"""Collapse great-docs' per-symbol API-reference pages into per-group pages.

great-docs emits one `.qmd` page per configured symbol, and splits any class
above `inline_methods` (default 5 methods) into extra `<Class> Methods` pages.
A curated `reference:` config of N symbols in titled groups therefore renders
far more than N pages through quarto/pandoc. This module rebinds a handful of
great-docs internals so each titled group renders as one anchored page:

- `Config.should_split_methods` -> always False, so class members embed inline
  instead of spilling into companion `<Class> Methods` sections.
- `api_reference.resolve` is wrapped to replace each group's single-symbol
  `Page`s with one flattened group `Page` (path = slug of the group title).
  `build()` references that module global, so `build_manifest`, `write_index`,
  `write_pages`, and the inventory all see the grouped tree — on both the
  dynamic build and the static-analysis fallback (both call the same `build()`).
- `RenderDoc.render_title` pins every symbol heading (members too) to
  `id=<doc.anchor>`; `RenderDoc.render_summary` re-points its links to match.
  Stock relies on Quarto's short-name auto-ids, which collide and never match
  the inventory URI `reference/<group>.html#<doc.anchor>`.
- `RenderAPIPage._has_one_object` -> False on a group page, so a lone symbol
  still renders its own anchored heading (stock suppresses it), and
  `RenderAPIPage.render_metadata` titles the page with the group name.
- `GreatDocs._update_sidebar_from_sections` points each symbol at
  `reference/<group>.qmd#<anchor>`, with a fragment-free group-page leaf per
  section so the pages get sidebar membership: a fragment-free leaf href is the
  shape that confers membership in a Quarto multi-sidebar site (section-level
  hrefs round-trip fine; they just don't confer membership).

Everything is gated by `gd_build.patches`; `install` validates then commits
(no half-patched interpreter on failure) and is idempotent, transforming only
when the config carries at least two titled groups (a curated grouped
reference), leaving autogenerated single-section references stock.
"""

from __future__ import annotations

import functools
import re
from collections.abc import Callable
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from great_docs._apiref._render.api_page import RenderAPIPage
    from great_docs._apiref._render.doc import RenderDoc
    from great_docs._apiref.content import Doc, Section
    from great_docs.core import GreatDocs

    Commit = tuple[object, str, object]

# Stashed on a grouped `Page` instance (not a dataclass field, so the manifest
# visitor ignores it) to carry the group title through to page rendering.
GROUP_TITLE_ATTR = "gd_group_title"

# Marks a wrapped callable so a second `install()` does not double-wrap.
MARK = "gd_grouped"

RENDER_DOC_CLASSES = ("RenderDocClass", "RenderDocFunction", "RenderDocAttribute", "RenderDocModule")


def slug(title: str) -> str:
    """A stable, filesystem- and URL-safe slug of a group title"""
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "group"


def anchor(package: str | None, name: str) -> str:
    """The dotted `doc.anchor` great-docs resolves a curated symbol to

    Mirrors `resolve._join_path(package, name)` normalized to griffe's dotted
    form: for a real member this equals the object's accessed `obj.path`, which
    the inventory URI and the grouped heading id both carry. A null/absent
    package (a per-item `package: null`) yields the bare name, as `_join_path`
    does.
    """
    if not package:
        return name
    joined = f"{package}.{name}" if (":" in package or ":" in name) else f"{package}:{name}"
    return joined.replace(":", ".")


def should_group(titles: list[str | None]) -> bool:
    """Whether to collapse — only a curated reference with >=2 titled groups"""
    return len([t for t in titles if t]) >= 2


def single_symbol_doc(entry: object) -> Doc | None:
    """The lone `Doc` of a stock single-symbol top-level `Page`, else None

    Leaves `Text`, `MemberPage`, and any multi-object page untouched.
    """
    from great_docs._apiref.content import Doc, Page

    if type(entry) is Page and len(entry.contents) == 1 and isinstance(entry.contents[0], Doc):
        return entry.contents[0]
    return None


def member_anchors(docs: list[Doc]) -> set[str]:
    """Every anchor reachable through the `members` of the given docs, recursively"""
    found: set[str] = set()
    stack = list(docs)
    while stack:
        for member in getattr(stack.pop(), "members", None) or []:
            anchor_val = getattr(member, "anchor", None)
            if anchor_val:
                found.add(anchor_val)
            stack.append(member)
    return found


def group_sections(sections: list[Section]) -> list[Section]:
    """Replace each titled section's single-symbol pages with one group page"""
    from great_docs._apiref.content import Page

    if not should_group([section.title for section in sections]):
        return sections

    out: list[Section] = []
    slugs: dict[str, str] = {}
    for section in sections:
        title = section.title
        docs = [d for e in section.contents if (d := single_symbol_doc(e)) is not None]
        if not title or not docs:
            out.append(section)
            continue

        # Drop a top-level copy of a symbol also embedded as a curated class's
        # member (e.g. BaseHookEvent.as_input), so its anchor stays unique.
        embedded = member_anchors(docs)
        docs = [doc for doc in docs if getattr(doc, "anchor", None) not in embedded]
        if not docs:
            out.append(section)
            continue

        group_slug = slug(title)
        if group_slug in slugs:
            raise ValueError(
                f"grouped-reference: {slugs[group_slug]!r} and {title!r} both slug to "
                f"{group_slug!r} — give one a distinct title"
            )
        slugs[group_slug] = title

        page = Page(path=group_slug, flatten=True, contents=docs)
        setattr(page, GROUP_TITLE_ATTR, title)
        # Preserve order: the group page takes the first collapsed slot; other
        # single-symbol pages fold into it, everything else keeps its place.
        placed = False
        rebuilt: list[object] = []
        for entry in section.contents:
            if single_symbol_doc(entry) is None:
                rebuilt.append(entry)
            elif not placed:
                rebuilt.append(page)
                placed = True
        out.append(section.replace(contents=rebuilt))

    return out


def grouped_update_sidebar(instance: GreatDocs, original: Callable[[GreatDocs], None]) -> None:
    """Point each configured symbol at its group page anchor in the Quarto sidebar

    Runs in place of `GreatDocs._update_sidebar_from_sections` (which materializes
    `reference/<symbol>.qmd` per symbol from config, before the reference build).
    Falls back to the stock method whenever the config is not a curated grouped
    reference.
    """
    import great_docs.core as core
    from great_docs._translations import get_translation

    quarto_yml = instance.project_path / "_quarto.yml"
    if not quarto_yml.exists():
        return original(instance)

    with open(quarto_yml) as f:
        config = core.read_yaml(f) or {}

    apiref = config.get("api-reference")
    if not isinstance(apiref, dict) or "sections" not in apiref:
        return original(instance)

    sections = apiref["sections"]
    titles = [section.get("title") for section in sections if isinstance(section, dict)]
    if not should_group(titles):
        return original(instance)

    package = apiref.get("package") or ""
    api_index_label = get_translation("api_index", instance._config.language)
    contents: list[object] = [{"text": api_index_label, "href": "reference/index.qmd"}]

    for section in sections:
        title = section.get("title")
        section_pkg = section.get("package", package)
        # A fragment-free leaf href is the shape that confers sidebar membership
        # in a Quarto multi-sidebar site (section-level hrefs round-trip fine;
        # they just don't confer membership).
        entries: list[object] = (
            [{"text": title, "href": f"reference/{slug(title)}.qmd"}] if title else []
        )
        for item in section.get("contents", []):
            if isinstance(item, dict):
                name = item.get("name", str(item))
                item_pkg = item.get("package", section_pkg)
            else:
                name, item_pkg = item, section_pkg
            if title:
                href = f"reference/{slug(title)}.qmd#{anchor(item_pkg, name)}"
                entries.append({"text": name, "href": href})
            else:
                entries.append(f"reference/{name}.qmd")
        contents.append({"section": title, "contents": entries})

    config.setdefault("website", {})["sidebar"] = [{"id": "reference", "contents": contents}]
    instance._write_quarto_yml(quarto_yml, config)


def prepare_split_methods() -> list[Commit]:
    from great_docs.config import Config

    base = Config.should_split_methods
    if getattr(base, MARK, False):
        return []

    @functools.wraps(base)
    def should_split_methods(self: Config, method_count: int) -> bool:
        return False

    setattr(should_split_methods, MARK, True)
    return [(Config, "should_split_methods", should_split_methods)]


def prepare_resolve() -> list[Commit]:
    import great_docs._apiref.api_reference as ar

    base = ar.resolve
    if getattr(base, MARK, False):
        return []

    @functools.wraps(base)
    def resolve(*args: object, **kwargs: object) -> list[Section]:
        return group_sections(base(*args, **kwargs))

    setattr(resolve, MARK, True)
    return [(ar, "resolve", resolve)]


def prepare_render_titles() -> list[Commit]:
    import great_docs._apiref._render as render
    from great_docs._apiref.pandoc.blocks import Header
    from great_docs._apiref.pandoc.components import Attr

    commits: list[Commit] = []
    for name in RENDER_DOC_CLASSES:
        cls = getattr(render, name)
        base = cls.render_title
        if getattr(base, MARK, False):
            continue

        def make(base_fn: Callable[[RenderDoc], object]) -> Callable[[RenderDoc], object]:
            @functools.wraps(base_fn)
            def render_title(self: RenderDoc) -> object:
                result = base_fn(self)
                # Pin every symbol heading (members too) to doc.anchor — the
                # inventory URI and summary/sidebar links all target it.
                if isinstance(result, Header) and self.doc.anchor:
                    if result.attr is None:
                        result.attr = Attr(identifier=self.doc.anchor)
                    elif result.attr.identifier is None:
                        result.attr.identifier = self.doc.anchor
                return result

            setattr(render_title, MARK, True)
            return render_title

        commits.append((cls, "render_title", make(base)))
    return commits


def prepare_render_summary() -> list[Commit]:
    import great_docs._apiref._render as render
    from great_docs._apiref._format import markdown_escape
    from great_docs._apiref.pandoc.components import Attr
    from great_docs._apiref.pandoc.inlines import Link

    commits: list[Commit] = []
    for name in RENDER_DOC_CLASSES:
        cls = getattr(render, name)
        if getattr(cls.render_summary, MARK, False):
            continue

        def render_summary(self: RenderDoc) -> object:
            # Anchor every row (members too) to doc.anchor, matching the pinned
            # heading id; stock links contained members to their short name.
            link = Link(
                markdown_escape(self.summary_name),
                f"{self.page_path}#{self.doc.anchor}",
                attr=Attr(classes=[f"doc-{self.kind}", "doc-label", f"doc-label-{self.label}"]),
            )
            return [(str(link), self.docstring_subject)]

        setattr(render_summary, MARK, True)
        commits.append((cls, "render_summary", render_summary))
    return commits


def prepare_page_metadata() -> list[Commit]:
    import great_docs._apiref._render as render
    from great_docs._apiref.pandoc.blocks import Meta

    cls = render.RenderAPIPage
    base = cls.render_metadata
    if getattr(base, MARK, False):
        return []

    @functools.wraps(base)
    def render_metadata(self: RenderAPIPage) -> object:
        title = getattr(self.page, GROUP_TITLE_ATTR, None)
        if title:
            return Meta({"title": title, "body-classes": "doc-api-page"})
        return base(self)

    setattr(render_metadata, MARK, True)
    return [(cls, "render_metadata", render_metadata)]


def prepare_has_one_object() -> list[Commit]:
    import great_docs._apiref._render as render

    cls = render.RenderAPIPage
    base = cls._has_one_object
    getter = base.fget if isinstance(base, property) else base
    if getattr(getter, MARK, False):
        return []

    @functools.wraps(getter)
    def _has_one_object(self: RenderAPIPage) -> bool:
        # A grouped page is never single-object: a lone symbol must still render
        # its own anchored heading rather than have its title suppressed.
        if getattr(self.page, GROUP_TITLE_ATTR, None):
            return False
        return getter(self)

    setattr(_has_one_object, MARK, True)
    return [(cls, "_has_one_object", property(_has_one_object))]


def prepare_sidebar() -> list[Commit]:
    from great_docs.core import GreatDocs

    base = GreatDocs._update_sidebar_from_sections
    if getattr(base, MARK, False):
        return []

    @functools.wraps(base)
    def update_sidebar_from_sections(self: GreatDocs) -> None:
        return grouped_update_sidebar(self, base)

    setattr(update_sidebar_from_sections, MARK, True)
    return [(GreatDocs, "_update_sidebar_from_sections", update_sidebar_from_sections)]


def install() -> None:
    """Rebind every great-docs internal the grouped-reference layout depends on

    Validate-then-commit: all imports, lookups, and wrapper construction run
    first; the attribute assignments happen only once every wrapper is built, so
    a failure never leaves a half-patched interpreter.
    """
    commits: list[Commit] = []
    for prepare in (
        prepare_split_methods,
        prepare_resolve,
        prepare_render_titles,
        prepare_render_summary,
        prepare_page_metadata,
        prepare_has_one_object,
        prepare_sidebar,
    ):
        commits.extend(prepare())
    for owner, attr, value in commits:
        setattr(owner, attr, value)
