fragments = [
  "cc-skills-intro",
  "cc-skills:ask-before-assuming",
  "cc-skills:code-review-response",
  "cc-skills:parallelize",
  "cc-skills:writing-plans",
  "cc-skills:ccx",
  "cc-skills-style",
  "cc-skills:version-control",
]

[sources.cc-skills]
source = "github:yasyf/cc-skills@main"
